### ISSUE TITLE
nvm environment variable

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/laptop#97] opened 2016-11-28 18:42 UTC
export NVM_DIR="/Users/mathewcaughron/.nvm"
If you are reporting an issue with the script, please fill out the details
below to help us troubleshoot the error.

### Did you have any of the following tools installed before running the script?

- Xcode
- Apple's command line tools
- Anything the script installs (see "What it sets up" in the README)

### Copy and paste the entire contents of laptop.log, or attach it

**Comment by monfresh** [comment] 2016-11-28 20:16
I'm assuming this is a duplicate of #98, so I'm closing it. Feel free to reopen if it's a different issue.

**Closed by monfresh** 2016-11-28 20:16 UTC
